---
- name: Demo Block Rescue Always
  hosts: all
  vars:
    build: failed
  tasks:
    - name: Attempt to deploy new code build
      block:
        - name: Install New Code Build (Block Task)
          debug:
            msg: Deploying new code build ... multiple steps. (Block Task)
        - name: Trigger Failure (Block Task)
          ansible.builtin.fail:
            msg: The system may not be provisioned according to the CMDB status. (Block Task)
          when: build != "success"
      rescue:
        - name: Reverting to previous build (Rescue Task)
          debug:
            msg: Contacting Git or whatever and performing steps to revert to previous build. (Rescue Task)

      always:
        - name: Restating services based on build (Always Task)
          debug:
            msg: Performing steps to restart needed services based on build. (Always Task)
