pkg_list:
  - httpd
  - firewalld
  - mod_ssl
  - tree
  - vim

pkg_dict_list:
  - pkg_group: web1
    web_pkg: nginx 
    firewall_pkg: firewalld
    editor: vim
    
  - pkg_group: web2
    web_pkg: httpd 
    firewall_pkg: firewalld
    editor: nano