---
# First Play
- name: First Play of Playbook - Show items in list and dictionary
  hosts: localhost
  gather_facts: true
  vars_files:
    - packages_to_install.yaml
  tasks:
    - name: Dump list 
      debug:
        var: pkg_list
    - name: Dump Dictionary List 
      debug:
        var: pkg_dict_list
    - name: Dump Dictionary List of just web packages
      debug:
        msg: The web packages are {{ pkg_dict_list | selectattr('web_pkg', 'defined') | map(attribute='web_pkg') }}
    - name: Dump Dictionary List of just Package Groups
      debug:
        msg: The web package group names are {{pkg_dict_list | selectattr('pkg_group', 'defined') | map(attribute='pkg_group') }}
      when: "'web1' in  pkg_dict_list  | map(attribute='pkg_group')"

    - name: Dump Dictionary List of Package Groups List
      debug:
        msg: The web package groups are {{ item }}
      loop: "{{ pkg_dict_list  | map(attribute='pkg_group') }}"
