---
# First Play
- name: First Play of Playbook - Show items in list and dictionary
  hosts: localhost
  gather_facts: true
  vars_files:
    - packages_to_install.yaml
  tasks:
    - name: Dump list 
      debug:
        var: pkg_list
    - name: Dump Dictionary List 
      debug:
        var: pkg_dict_list

    - name: Dump Dictionary List of just web packages
      debug:
        msg: The web package is {{ item.value.web_pkg }} for {{ item.key }}
      loop: "{{ pkg_dict_list | dict2items }}"

    - name: Dump Dictionary web Pacakage for Web1
      debug:
        msg: The web package is {{ item.value.web_pkg }} for {{ item.key }}
      loop: "{{ pkg_dict_list | dict2items }}"
      when: "'web1' in item.key"
