---
- name: Demo Handlers
  hosts: servera
  tasks:
    - name: Remove file on servera
      ansible.builtin.file:
        path: /etc/handler.txt
        state: absent
      notify: I was triggered


  handlers:
    - name: I was triggered
      debug:
        msg: The handler was triggered
