---
- name: Demo Handlers
  hosts: servera
  tasks:
    - name: Create file on servera
      ansible.builtin.copy:
        content: I'm a file created to see if a handler is triggered.
        dest: /etc/handler.txt
      notify: Another handler not triggered


  handlers:
    - name: I was triggered
      debug:
        msg: The handler was triggered

    - name: Another handler not triggered
      debug:
        msg: I'm another handler and I wasn't triggered
