---
- name: Create Sudoers File
  hosts: servera.lab.example.com

  tasks:
    - name: Show user for the task with Become=True
      ansible.builtin.shell: |
        whoami
      become: true
      register: username

    - name: Display User with play Become=True
      ansible.builtin.debug:
        msg: My user for Become=True is {{ username.stdout }}

    - name: Show user for the task with Become=False
      ansible.builtin.shell: |
        whoami
      become: false
      register: username

    - name: Display User with play Become=false
      ansible.builtin.debug:
        msg: My user for Become=false is {{ username.stdout }}
